// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:7a457959-5bc7-4134-9370-a008ab517339',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ionfullappproversion-hosting-mobilehub-921105249',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dv8jgkzxov9hy.cloudfront.net',
    'aws_mobile_analytics_app_id': '3b580b29a7b74545a586e58e92faa8cf',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '48b119b8-2bde-11e8-a6ca-85a13b734c82',
    'aws_project_name': 'ion2FullApp-PRO-version-2018-03-19-18-30-23',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'ionfullappproversion-mobilehub-921105249',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_CmQLhXc1P',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '19bhhoglhkfp3ciqgm6sieofag',
}

export default awsmobile;
